// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://acdwbktxqvxzxrdgiofm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFjZHdia3R4cXZ4enhyZGdpb2ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODAyODcsImV4cCI6MjA3MjY1NjI4N30.v5o1syU6ojoX3DE6iLqRQc5vO-GMGONH1DFabzThuyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});